name: build, test and publish container
on: [push]
jobs:
 build-test-and-publish-container:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - uses: azure/docker-login@v1
      with:
        login-server: idi2020.azurecr.io
        username: ${{ secrets.IDI2020_REGISTRY_USERNAME }}
        password: ${{ secrets.IDI2020_REGISTRY_PASSWORD }}
    - name: install dotnet environment
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    - name: build project
      run: dotnet publish -o ../containerbuild/release/
      working-directory: ./Assignment1
    - name: Add SQL Instanze
      run: sudo service mysql stop
    - uses: getong/mariadb-action@v1.1
      with:
        host port: 3307
        container port: 3307 # Optional, default value is 3306. The port of container
        character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
        collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
        mariadb version: '10.4.10' # Optional, default value is "latest". The version of the MariaDB
        mysql database: 'logbook' # Optional, default value is "test". The specified database which will be create
        mysql user: 'root' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
        mysql password: 'root'
    - name: run test
      run: dotnet test
      working-directory: ./TestProject1
    - run: chmod +x ./containerbuild/build-container.sh
    - name: build docker container
      run: ./build-container.sh build1
      working-directory: ./containerbuild
#  run: make
#  - name: build and publish container
#  run: ./build.sh build-$GITHUB_RUN_NUMBER idi2020.azurecr.io